### ISSUE TITLE
Stackblitz REPLs not working on Firefox

### ISSUE THREAD

**Issue by jpaquim** [Rich-Harris/svelte-cubed#11]
Introduced with https://github.com/Rich-Harris/svelte-cubed/commit/b002447dbf4e59cf10467aa60df703c88e1fa7f8

Firefox still has [no support for WebContainers](https://developer.stackblitz.com/docs/platform/browser-support/), it might make sense to keep the Svelte REPL links as fallback for non-Chrome browsers at the moment.

**Comment by Rich-Harris** [comment]
Unfortunately this library stopped working in the REPL (#14) — something to do with unpkg resolving to the non-ESM build, or something — and so that's not an option, unfortunately. The best alternative for people who can't use Chromium for whatever reason is probably to create a project locally with `npm init svelte@next`.

**Comment by jpaquim** [comment]
Ok, thanks for the feedback.

From what I can tell (Firefox on Linux right now), the Svelte REPL examples seem to be working correctly, there seems to be a lengthy bundling step happening whenever I make a change in the code, but otherwise it renders well. Let me know if I can help with debugging in any way.
